postgres-data:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
  container_name: postgres-datastore-metrixir

postgresql:
  image: postgres
  environment:
    POSTGRES_USER: metrixir
    POSTGRES_PASSWORD: p@ssw0rd
  ports:
    - "5432:5432"
  container_name: postgres-db-metrixir
  volumes_from:
      - postgres-data
